#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
CONFIG_DIR="$HOME/.config/agent-telemetry"
CONFIG_FILE="$CONFIG_DIR/config.toml"
SERVE_LABEL="io.github.originallgb.codexbar-serve"
BRIDGE_LABEL="io.github.originallgb.agent-telemetry"
HOST_ID=$(scutil --get LocalHostName 2>/dev/null || hostname -s)
LAUNCH_DOMAIN="gui/$(id -u)"

wait_for_bootout() {
  local label="$1"
  local _
  for _ in {1..30}; do
    launchctl print "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || return 0
    sleep 0.2
  done
  return 1
}

install_agent() {
  local label="$1" template="$2"
  local target="$HOME/Library/LaunchAgents/$label.plist"
  local source
  mkdir -p "$HOME/Library/LaunchAgents"
  source=$(mktemp)
  sed -e "s#__HOME__#$HOME#g" -e "s#__REPO__#$ROOT_DIR#g" "$template" >"$source"
  if [[ ! -f "$target" ]] || ! cmp -s "$source" "$target"; then
    launchctl bootout "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
    wait_for_bootout "$label" || true
    install -m 600 "$source" "$target"
    launchctl bootstrap "$LAUNCH_DOMAIN" "$target"
  elif ! launchctl print "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1; then
    launchctl bootstrap "$LAUNCH_DOMAIN" "$target"
  fi
  rm -f "$source"
}

verify_retained_entities() {
  MQTT_HOST="$MQTT_HOST" MQTT_PORT="$MQTT_PORT" MQTT_USERNAME="$MQTT_USERNAME" \
    MQTT_PASSWORD="$MQTT_PASSWORD" "$ROOT_DIR/.venv/bin/python" - <<'PY'
import json
import os
import threading
import time
import uuid

import paho.mqtt.client as mqtt

host = os.environ["MQTT_HOST"]
port = int(os.environ["MQTT_PORT"])
username = os.environ["MQTT_USERNAME"]
password = os.environ["MQTT_PASSWORD"]
connected = threading.Event()
configs = set()
states = set()

client = mqtt.Client(
    mqtt.CallbackAPIVersion.VERSION2,
    client_id=f"agent-telemetry-verify-{uuid.uuid4().hex[:10]}",
)
client.username_pw_set(username, password)

def on_connect(client, userdata, flags, reason_code, properties=None):
    del userdata, flags, properties
    code = int(getattr(reason_code, "value", reason_code))
    if code != 0:
        print(f"MQTT authorization failed with reason code {code}")
        connected.set()
        return
    client.subscribe("homeassistant/sensor/#", qos=1)
    client.subscribe("agent_telemetry/#", qos=1)
    connected.set()

def on_message(client, userdata, message):
    del client, userdata
    if not message.retain:
        return
    if message.topic.startswith("homeassistant/sensor/") and message.topic.endswith("/config"):
        try:
            payload = json.loads(message.payload)
        except json.JSONDecodeError:
            return
        unique_id = payload.get("unique_id")
        if isinstance(unique_id, str) and unique_id.startswith("agent_telemetry_"):
            configs.add(unique_id)
    elif message.topic.startswith("agent_telemetry/"):
        states.add(message.topic)

client.on_connect = on_connect
client.on_message = on_message
client.connect(host, port, keepalive=30)
client.loop_start()
if not connected.wait(10):
    raise SystemExit("Timed out connecting to MQTT")
time.sleep(6)
client.disconnect()
client.loop_stop()

print(f"Retained discovery configs: {len(configs)}")
print(f"Retained state/attribute topics: {len(states)}")
if len(configs) < 17 or len(states) < 26:
    raise SystemExit("Expected at least 17 discovery configs and 26 state/attribute topics")
PY
}

banner "Agent telemetry · MQTT + Home Assistant"

stage "Broker credentials"
say "Enter the dedicated Mosquitto credentials you already have."
note "The password is hidden and is never placed in a command line or printed."
ask MQTT_HOST "MQTT host (Home Assistant broker address):"
ask MQTT_PORT "MQTT port [1883]:"
MQTT_PORT=${MQTT_PORT:-1883}
ask MQTT_USERNAME "MQTT username:"
ask_secret MQTT_PASSWORD "MQTT password:"
[[ -n "$MQTT_HOST" ]] || { warn "MQTT host is required"; exit 1; }
[[ -n "$MQTT_USERNAME" ]] || { warn "MQTT username is required"; exit 1; }
[[ -n "$MQTT_PASSWORD" ]] || { warn "MQTT password is required"; exit 1; }

stage "Authenticated retained round trip"
say "The wizard will publish one unique retained acceptance message, read it from a fresh client, then clear it."
MQTT_HOST="$MQTT_HOST" MQTT_PORT="$MQTT_PORT" MQTT_USERNAME="$MQTT_USERNAME" \
  MQTT_PASSWORD="$MQTT_PASSWORD" "$ROOT_DIR/.venv/bin/python" - <<'PY'
import os
import threading
import uuid

import paho.mqtt.client as mqtt

host = os.environ["MQTT_HOST"]
port = int(os.environ["MQTT_PORT"])
username = os.environ["MQTT_USERNAME"]
password = os.environ["MQTT_PASSWORD"]
topic = f"agent_telemetry/_acceptance/{uuid.uuid4().hex}"
payload = "agent-telemetry-acceptance-v1"

def connect(client):
    ready = threading.Event()
    result = {}
    def on_connect(client, userdata, flags, reason_code, properties=None):
        del client, userdata, flags, properties
        result["code"] = int(getattr(reason_code, "value", reason_code))
        ready.set()
    client.on_connect = on_connect
    client.username_pw_set(username, password)
    client.connect(host, port, keepalive=30)
    client.loop_start()
    if not ready.wait(10):
        raise RuntimeError("MQTT connection timed out")
    if result["code"] != 0:
        raise RuntimeError(f"MQTT authorization failed with reason code {result['code']}")

publisher = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id=f"at-pub-{uuid.uuid4().hex[:10]}")
subscriber = None
cleaner = None
published = False
try:
    connect(publisher)
    info = publisher.publish(topic, payload, qos=1, retain=True)
    info.wait_for_publish(10)
    if not info.is_published():
        raise RuntimeError("Retained publish did not complete")
    published = True
    publisher.disconnect()
    publisher.loop_stop()

    received = []
    got_message = threading.Event()
    subscriber = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id=f"at-sub-{uuid.uuid4().hex[:10]}")
    def on_message(client, userdata, message):
        del client, userdata
        received.append((message.payload.decode(), message.retain))
        got_message.set()
    subscriber.on_message = on_message
    connect(subscriber)
    subscriber.subscribe(topic, qos=1)
    if not got_message.wait(10):
        raise RuntimeError("Fresh subscriber did not receive the retained message")
    if received != [(payload, True)]:
        raise RuntimeError("Retained payload or retain flag did not match")
finally:
    try:
        publisher.disconnect(); publisher.loop_stop()
    except Exception:
        pass
    if subscriber is not None:
        try:
            subscriber.disconnect(); subscriber.loop_stop()
        except Exception:
            pass
    if published:
        cleaner = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id=f"at-clean-{uuid.uuid4().hex[:10]}")
        connect(cleaner)
        info = cleaner.publish(topic, None, qos=1, retain=True)
        info.wait_for_publish(10)
        cleaner.disconnect(); cleaner.loop_stop()

print("Authenticated retained publish, fresh subscribe, and cleanup succeeded.")
PY

stage "Protected local configuration"
say "The verified values will now be written to $CONFIG_FILE with owner-only permissions."
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
MQTT_HOST="$MQTT_HOST" MQTT_PORT="$MQTT_PORT" MQTT_USERNAME="$MQTT_USERNAME" \
  MQTT_PASSWORD="$MQTT_PASSWORD" CONFIG_FILE="$CONFIG_FILE" HOST_ID="$HOST_ID" python3 - <<'PY'
import json
import os
from pathlib import Path

path = Path(os.environ["CONFIG_FILE"])
tmp = path.with_suffix(".toml.tmp")
quote = json.dumps
text = f'''[codexbar]
url = "http://127.0.0.1:8899/usage"
poll_interval_seconds = 30
request_timeout_seconds = 40

[mqtt]
host = {quote(os.environ["MQTT_HOST"])}
port = {int(os.environ["MQTT_PORT"])}
username = {quote(os.environ["MQTT_USERNAME"])}
password = {quote(os.environ["MQTT_PASSWORD"])}
client_id = {quote("agent-telemetry-" + os.environ["HOST_ID"])}

[telemetry]
host_id = {quote(os.environ["HOST_ID"])}
topic_prefix = "agent_telemetry"
discovery_prefix = "homeassistant"
'''
tmp.write_text(text)
tmp.chmod(0o600)
tmp.replace(path)
PY
chmod 600 "$CONFIG_FILE"
say "✓ wrote protected configuration"

stage "Install and start the bridge"
say "This validates the local cached source, installs both per-user LaunchAgents, and starts the MQTT bridge."
cd "$ROOT_DIR"
uv sync --quiet
"$ROOT_DIR/.venv/bin/python" agent_telemetry.py --config "$CONFIG_FILE" --validate
touch "$HOME/Library/Logs/agent-telemetry.log" "$HOME/Library/Logs/agent-telemetry.error.log"
chmod 600 "$HOME/Library/Logs/agent-telemetry.log" "$HOME/Library/Logs/agent-telemetry.error.log"
install_agent "$SERVE_LABEL" "$ROOT_DIR/launchd/$SERVE_LABEL.plist"
install_agent "$BRIDGE_LABEL" "$ROOT_DIR/launchd/$BRIDGE_LABEL.plist"
launchctl print "$LAUNCH_DOMAIN/$SERVE_LABEL" >/dev/null
launchctl print "$LAUNCH_DOMAIN/$BRIDGE_LABEL" >/dev/null
say "✓ both LaunchAgents are loaded"

stage "Verify retained Home Assistant entities"
say "The bridge must expose at least 17 discovery configs and 26 retained state/attribute topics."
verify_retained_entities
open_url "http://homeassistant:8123"
step "Log in, then open Settings → Devices & services → Devices."
step "Open ‘Agent telemetry ($HOST_ID)’ and confirm the Codex, Claude, Antigravity, reset-time, and reset-credit entities."
pause "Press Enter after the device and entities are visible."

stage "Broker restart acceptance"
warn "This stage intentionally restarts Mosquitto through Home Assistant."
open_url "http://homeassistant:8123"
step "Open Settings → Add-ons → Mosquitto broker."
if confirm "Restart the Mosquitto broker now and continue once it reports Running?"; then
  pause "Press Enter when Mosquitto reports Running again."
  verify_retained_entities
  say "✓ retained discovery and state survived or were restored after broker restart"
else
  SKIPPED+=("Mosquitto broker restart acceptance")
  warn "broker restart acceptance skipped"
fi

finish
note "Configuration: $CONFIG_FILE"
note "Status: $ROOT_DIR/docs/implementation-status.md"
